#!/bin/bash

set -e

# Add global config
cat << EOF > /etc/samba/smb.conf

[global]
workgroup = WORKGROUP
server string = Samba Shares
netbios name = Samba Shares
security = user
map to guest = bad user
dns proxy = no
printing = bsd
printcap name = /dev/null
idmap uid = 1000
idmap gid = 1000
socket options = TCP_NODELAY SO_RCVBUF=65535 SO_SNDBUF=65535

EOF

# Add share config
for share in ${@// / }; do
  shareConfig=(${share//:/ })
  cat << EOF >> /etc/samba/smb.conf
[${shareConfig[0]}]
path = ${shareConfig[1]}
browsable = yes
writable = yes
guest ok = yes
read only = no

EOF
done

# Start samba
service nmbd start
smbd -F
